#!/usr/bin/env bash
# be sure opyright and language team is correct

set -euo pipefail

TRANSLATION_DIR="po"
POT_FILE="$TRANSLATION_DIR/bodhi-update-manager.pot"
FILE_LIST="$TRANSLATION_DIR/POTFILES.in"
APP_DIR="data/applications/"
DESKTOP_TEMPLATE="$APP_DIR/bodhi-update-manager.in"
XDG_TEMPLATE="$APP_DIR/bodhi-update-manager-tray.in"
DESKTOP_OUTPUT="$APP_DIR/bodhi-update-manager.desktop"
XDG_OUTPUT="$APP_DIR/bodhi-update-manager-tray.desktop"
VERSION=$(PYTHONPATH=src python3 -c 'from bodhi_update._version import __version__; print(__version__)')

check_command() {
    if ! command -v "$1" >/dev/null 2>&1; then
        echo "$1 could not be found."
        echo "You can install it with: sudo apt install gettext"
        exit 255
    fi
}

check_command xgettext
check_command msgmerge
check_command msginit
check_command msgfmt

if [[ ! -f "$TRANSLATION_DIR/LINGUAS" ]]; then
    echo "Missing $TRANSLATION_DIR/LINGUAS"
    exit 1
fi

if [[ ! -f "$FILE_LIST" ]]; then
    echo "Missing $FILE_LIST"
    exit 1
fi

mapfile -t langs < <(grep -vE '^\s*($|#)' "$TRANSLATION_DIR/LINGUAS")

echo "Updating POT file"

xgettext \
  --language=Python \
  --from-code=UTF-8 \
  --keyword=_ \
  --keyword=N_ \
  --keyword=ngettext:1,2 \
  --package-name="bodhi-update-manager" \
  --package-version="$VERSION" \
  --msgid-bugs-address="https://github.com/flux-abyss/bodhi-update-manager/issues" \
  -o "$POT_FILE" \
  --files-from="$FILE_LIST"

xgettext \
  --join-existing \
  --language=Desktop \
  --from-code=UTF-8 \
  -o "$POT_FILE" \
  "$DESKTOP_TEMPLATE"
  
xgettext \
  --join-existing \
  --language=Desktop \
  --from-code=UTF-8 \
  -o "$POT_FILE" \
  "$XDG_TEMPLATE"

sed -i 's/^# Copyright (C) YEAR THE PACKAGE'\''S COPYRIGHT HOLDER/# Copyright (C) 2026 Bodhi Linux Team/' "$POT_FILE"

for lang in "${langs[@]}"; do
    po_file="$TRANSLATION_DIR/$lang.po"

    if [[ -f "$po_file" ]]; then
        echo "Updating $lang.po"
        msgmerge --update "$po_file" "$POT_FILE"
    else
        echo "Creating $lang.po"
        msginit \
            --input="$POT_FILE" \
            --locale="$lang" \
            --output-file="$po_file" \
            --no-translator \
            --package-name="bodhi-update-manager"
        # Set Language-Team
        sed -i "s/^\"Language-Team:.*\"/\"Language-Team: Bodhi Team\\\\n\"/" "$po_file"
    fi
done

echo "Generating translated desktop files"
msgfmt \
  --desktop \
  --template="$DESKTOP_TEMPLATE" \
  -d "$TRANSLATION_DIR" \
  -o "$DESKTOP_OUTPUT"

msgfmt \
  --desktop \
  --template="$XDG_TEMPLATE" \
  -d "$TRANSLATION_DIR" \
  -o "$XDG_OUTPUT"
